FROM debian:stable

LABEL maintainer="oprax@me.com" 

RUN apt update && apt upgrade -y
RUN apt install -y gnupg openssl openssh-client git ca-certificates curl wget lsb-release apt-transport-https apt-utils

